name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Commit resume
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          mkdir -p build && mv resume.pdf build/
          git add build/resume.pdf
          git commit -m "Update compiled pdf"
      - name: Push resume
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
